### ISSUE TITLE
Facing "use of closed network connection."

### ISSUE THREAD

**Issue by ziqingyuan** [SigNoz/signoz-otel-collector#247]
Hi SigNoz team 👋 !

Getting following error from signoz otel collector:

`info exporterhelper/retry sender.go:177 Exportinq failed. Will retry the request after interval
¡"kind": "exporter", "data type": "logs"
"name": "clickhouseloqsexporter" , "error": "StatementSend:read: read top
xxx.xxx.xxx.xxx:xxxxx->xxx.xxx.xxx.xxx:9000: use of closed network connection"
"interval": "5.315178856s")`

Was wondering if you have seen this kind of error and if there's way to fix that. Really appreciated it!

Our structure and when did we observe this error: 
We deploy signoz chart in a eks cluster. This error shows up on a newly created signoz collector pod, during its self recovery after a pressure test. 

We have k8s-infra chart deployed in all of our clusters, signoz otel act like a central receiver receiver data from all those collectors. We have horizontal pod autoscaler for signoz collector.

**Comment by portersupport** [comment]
Hey folks - I'm seeing this too. I've increased the number of OTEL collectors to 3, but no dice.

**Comment by rudimk** [comment]
Hey folks - I'm seeing this too. I've increased the number of OTEL collectors to 3, but no dice.

**Comment by rudimk** [comment]
I'm also seeing errors in Clickhouse: 

```
2024.03.21 11:27:40.815417 [ 11 ] {090904ea-f1a3-4b52-b31b-7a4822f03260} <Error> TCPHandler: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket ([::ffff:10.42.5.21]:9000 -> [::ffff:10.42.5.19]:52950). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c800f1b in /usr/bin/clickhouse
1. DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000caa69a1 in /usr/bin/clickhouse
2. DB::WriteBufferFromPocoSocket::nextImpl() @ 0x000000000caa733e in /usr/bin/clickhouse
3. DB::TCPHandler::runImpl() @ 0x000000001292120f in /usr/bin/clickhouse
4. DB::TCPHandler::run() @ 0x0000000012933eb9 in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x00000000153a5a72 in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x00000000153a6871 in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0x000000001549f047 in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001549d67d in /usr/bin/clickhouse
9. ? @ 0x00007fc8b1cb0609
10. ? @ 0x00007fc8b1bd5353

2024.03.21 11:27:40.815703 [ 11 ] {090904ea-f1a3-4b52-b31b-7a4822f03260} <Warning> TCPHandler: Client has gone away.
```

**Comment by nityanandagohain** [comment]
Can you also share the number of clickhouse shard along with the resources allocated to it ?

**Comment by rudimk** [comment]
Hey @nityanandagohain so I figured it out. There was a single shard and it was configured to use up to 16GB RAM, with just 5-6 clusters throwing metrics at it. Now I had Prometheus installed on the same cluster and I noticed CPU usage for Clickhouse was high - nothing less than 96%. Figured this was an instance type problem - I was running this on `t3.xlarge` machines, which use general-purpose CPUs, and don't allow for CPU bursting beyond a certain point. Switched to `c6i` machines, and it's been running fine ever since! 

Will start sharding Clickhouse in a few days. Thanks for your help!

**Comment by srikanthccv** [comment]
Some internal points I shared with our team for the reason behind this and context deadline exceeded errors

- Context deadline exceeded
   - This happens when the ClickHouse is under resource limits and not able to process the inserts/selects and the query times out
   - Or the processing is taking so long in collector the, context.Context object times out the operation
       - This usually happens when data is big.
       - If you see this for span metrics (because the number of time series is unusually high for some rouge operations), please rollout restart all the collectors.
- Use of closed n/w connection
   - Either because of the cancelled context.
    - Or because the connection is terminated by k8s for heavy resource usage.
