### ISSUE TITLE
Running migration that has async and sync together.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz-otel-collector#435]
* Let's say I have to create a migration, that has drop materialized view, and creating it again.
* Sync dropping it is a async operation and creating it is a sync operation what is the proper way to do it ?

**Comment by srikanthccv** [comment]
Why do you want to drop and recreate the same? Are you talking about updating the materialised view that has additional items? In that case, dropping and creating a new one will result in data loss, which is a problem depending on the target table requirement. If the data loss is not a concern, you should let it run the way it is currently. If data loss is a concern we should be using https://clickhouse.com/docs/en/sql-reference/statements/alter/view instead of dropping and creating a new one.

**Comment by nityanandagohain** [comment]
No there won't be data loss, since we are just updating the MV and not the underlying table.

Yeah, I think modifying the view makes better sense. Let me try it out.

**Comment by srikanthccv** [comment]
>No there won't be data loss, since we are just updating the MV and not the underlying table.


When I say data loss, I mean the moment you drop mv, all the new inserts that happen on the main table do not have any trigger, and their transformed results (aggregation or plain) do not go to target table till the new mv gets created. There is going to be a period where no trigger happens b/w deleting and creating a new mv. Whether that loss is acceptable or not depends on the nature of the target table.

**Comment by nityanandagohain** [comment]
Sorry, I misinterpreted the drop. That period is acceptable I will make changes to update the mat view instead of dropping
